# Generated by Django 3.1.4 on 2021-01-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Arvind', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Rao', max_length=128),
        ),
    ]
